### ISSUE TITLE
"Clear action name" reducer case is mutating state

### ISSUE THREAD

**Issue by markerikson** [michaldudek/redux-promise-await-middleware#1]
These lines are mutating the existing state:

```js
        state.splice(index, 1)

        return [...state]
```

Instead, you could replace the entire case with:

```js
case config.clearActionName:
    return state.filter(item => item !== action.promise);
```

That's shorter _and_ safer.

**Comment by michaldudek** [comment]
Thanks for input, this is very much work in progress not meant for consumption yet :P

However, I think on the contrary:

```
        const index = state.indexOf(action.promise)
        if (index < 0) {
          return state
        }
```

If the promise is not in state then it will return original unmodified array (state). Using the one line `.filter` call would always return a new array (even if the same elements, the reference is changed).

```
        state.splice(index, 1)
        return [...state]
```

If it is in state it will return a new array without the promise. Just like `.filter` would. But I agree it's nicer to use filter, even if a fraction of nanosecond slower (having to do full foreach + state.length comparisons).

None of this really matters as this reducer is meant to be used only in server side pre-render so that rendering can wait for all async actions to be finished. But like I said, this is all very much work in progress :)

Anyway, thanks for input, I will change it to .filter.

**Comment by markerikson** [comment]
Yeah, I was a bit over-zealous with the "replace the entire case" comment.  The bit about mutating the existing state still stands.  But yes, if it's only meant for SSR work, then it's probably not going to be much of an issue :)
